#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Tk state=floating


xrandr --output DP-2 --right-of HDMI-0

xrandr --output DP-2 --mode 1920x1080 --rate 144
xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 100

/usr/bin/feh --bg-fill /home/jrt/Desktop/j4im3/Fondos/fondo.jpg &
~/.config/polybar/./launch.sh &
/usr/local/bin/picom &
wmname LG3D &
